remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

title: Matthew Newell
description: Senior Principal Engineer | AI Strategist | Systems Integration
google_analytics: # Add your ID here if you have one later
show_downloads: false